// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjvDBJ9YkKJ2pb4DqisfD5YjPNciMjnxM',
    appId: '1:887596284102:web:626aeb7ece44b6f6553fc7',
    messagingSenderId: '887596284102',
    projectId: 'e-commerce-capstone',
    authDomain: 'e-commerce-capstone.firebaseapp.com',
    storageBucket: 'e-commerce-capstone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLNMr8xGT-x2eEUXRzgoA4RpryEdJFeM',
    appId: '1:887596284102:android:4e6dad864b2e2cb8553fc7',
    messagingSenderId: '887596284102',
    projectId: 'e-commerce-capstone',
    storageBucket: 'e-commerce-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xQrGfoafWRymNbqZWKinAkfykshAQS4',
    appId: '1:887596284102:ios:9a9e398f17a64b3f553fc7',
    messagingSenderId: '887596284102',
    projectId: 'e-commerce-capstone',
    storageBucket: 'e-commerce-capstone.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7xQrGfoafWRymNbqZWKinAkfykshAQS4',
    appId: '1:887596284102:ios:c1e40dd129898c9d553fc7',
    messagingSenderId: '887596284102',
    projectId: 'e-commerce-capstone',
    storageBucket: 'e-commerce-capstone.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
